apiVersion: run.tanzu.vmware.com/v1alpha3
kind: TanzuKubernetesCluster
metadata:
  name: tkg-cluster-sjh
  namespace: tkg-ns-sjh
spec:
  distribution:
    version: v1.27.11+vmware.1-fips.1-tkg.2      
  topology:
    controlPlane:
      replicas: 1
      vmClass: best-effort-small
      storageClass: k8s-storage
    nodePools:
      - name: worker
        replicas: 2
        vmClass: best-effort-small
        storageClass: k8s-storage
  settings:
    network:
      cni:
        name: antrea
      pods:
        cidrBlocks: ["172.168.0.0/16"]
      services:
        cidrBlocks: ["10.96.0.0/12"]
      serviceDomain: cluster.local
    storage:
      defaultClass: k8s-storage

